// gRPC Service Load Test
// Generated by: /k6.plan scenario=load target=grpcbin.test.k6.io:9000 protocol=grpc sla=p95<200ms

import grpc from 'k6/net/grpc';
import { check, sleep } from 'k6';

const client = new grpc.Client();
client.load(['definitions'], 'hello.proto');

export const options = {
  stages: [
    { duration: '2m', target: 30 },
    { duration: '5m', target: 30 },
    { duration: '2m', target: 0 },
  ],
  thresholds: {
    'grpc_req_duration': ['p(95)<200'],
    'grpc_req_failed': ['rate<0.01'],
  },
};

export default function grpcBasicServiceScenario() {
  client.connect('grpcbin.test.k6.io:9000', {
    plaintext: true,
    timeout: '30s',
  });

  const response = client.invoke('hello.HelloService/SayHello', {
    greeting: 'k6',
  });

  check(response, {
    'status is OK': (r) => r?.status === grpc.StatusOK,
    'has message': (r) => r?.message?.reply !== undefined,
  });

  client.close();
  sleep(1);
}
