// Comprehensive SLA Threshold Configuration
// Generated by: /k6.thresholds metrics=p95,p99,rate target=api-test.js

import http from 'k6/http';
import { check, sleep } from 'k6';

export const options = {
  stages: [
    { duration: '2m', target: 50 },
    { duration: '5m', target: 50 },
    { duration: '2m', target: 0 },
  ],
  
  thresholds: {
    // Response time percentiles - overall
    'http_req_duration': [
      'p(50)<200',     // Median < 200ms
      'p(90)<500',     // 90th percentile < 500ms
      'p(95)<800',     // 95th percentile < 800ms
      'p(99)<2000',    // 99th percentile < 2s
      'max<5000',      // Maximum < 5s
    ],
    
    // Error rate threshold
    'http_req_failed': [
      'rate<0.01',     // Total error rate < 1%
    ],
    
    // Request rate (throughput)
    'http_reqs': [
      'rate>20',       // Minimum 20 req/s
    ],
    
    // Check success rate
    'checks': [
      'rate>0.95',     // 95% of checks must pass
    ],
    
    // Per-endpoint thresholds using tags
    'http_req_duration{name:login}': [
      'p(95)<300',     // Login must be fast
    ],
    
    'http_req_duration{name:search}': [
      'p(95)<500',     // Search can be slightly slower
    ],
    
    'http_req_duration{name:checkout}': [
      'p(95)<1000',    // Checkout is complex
    ],
    
    // Connection and waiting time
    'http_req_connecting': [
      'p(95)<100',     // Connection time < 100ms
    ],
    
    'http_req_waiting': [
      'p(95)<500',     // Server response time < 500ms
    ],
    
    // TLS handshake time
    'http_req_tls_handshaking': [
      'p(95)<200',     // TLS handshake < 200ms
    ],
  },
};

export default function slaThresholdsScenario() {
  const demoPassword = __ENV.K6_DEMO_PASSWORD || '';

  // Login endpoint
  let response = http.post('https://httpbin.org/post', 
    JSON.stringify({ username: 'user', password: demoPassword }), 
    { 
      tags: { name: 'login' },
      headers: { 'Content-Type': 'application/json' },
    }
  );
  
  check(response, {
    'login successful': (r) => r.status === 200,
  });
  
  sleep(1);
  
  // Search endpoint 
  response = http.get('https://httpbin.org/get?q=test', {
    tags: { name: 'search' },
  });
  
  check(response, {
    'search returned data': (r) => r.status === 200,
  });
  
  sleep(1);
  
  // Checkout endpoint
  response = http.post('https://httpbin.org/post',
    JSON.stringify({ items: ['item1', 'item2'], total: 99.99 }),
    {
      tags: { name: 'checkout' },
      headers: { 'Content-Type': 'application/json' },
    }
  );
  
  check(response, {
    'checkout completed': (r) => r.status === 200,
  });
  
  sleep(2);
}
