// Browser User Journey Test
// Generated by: /k6.plan scenario=load target=https://test.k6.io protocol=browser sla=p95<3s

import { browser } from 'k6/browser';
import { check, sleep } from 'k6';

export const options = {
  scenarios: {
    ui: {
      executor: 'constant-vus',
      vus: 5,
      duration: '5m',
      options: {
        browser: {
          type: 'chromium',
        },
      },
    },
  },
  thresholds: {
    'browser_web_vital_lcp': ['p(95)<3000'],    // Largest Contentful Paint < 3s
    'browser_web_vital_fid': ['p(95)<100'],     // First Input Delay < 100ms
  },
};

export default async function userJourneyScenario() {
  const page = browser.newPage();

  try {
    // Navigate to homepage
    await page.goto('https://test.k6.io', {
      waitUntil: 'networkidle',
      timeout: '30s',
    });

    check(page, {
      'page loaded': page.locator('h1').textContent() !== '',
    });

    // Click login link
    await page.locator('a[href="/my_messages.php"]').click();
    await page.waitForSelector('input[name="login"]');

    // Fill login form
    await page.locator('input[name="login"]').type('admin');
    await page.locator('input[name="password"]').type('123');
    await page.locator('input[type="submit"]').click();

    // Verify login success
    check(page, {
      'logged in': page.locator('h2').textContent().includes('Welcome'),
    });

  } finally {
    page.close();
  }

  sleep(1);
}
