// Browser User Journey Test
// Generated by: /k6.plan scenario=load target=https://test.k6.io protocol=browser sla=p95<3s
// Updated: Uses environment variables for URL and authentication credentials
// Usage: k6 run --env BASE_URL=https://test.k6.io --env TEST_USER=admin --env TEST_PASSWORD=123 browser/user-journey.js

import { browser } from 'k6/browser';
import { check, sleep } from 'k6';

const baseUrl = __ENV.BASE_URL || 'https://test.k6.io';
const testUser = __ENV.TEST_USER || 'admin';
const testPassword = __ENV.TEST_PASSWORD || '123';

export const options = {
  scenarios: {
    ui: {
      executor: 'constant-vus',
      vus: 5,
      duration: '5m',
      options: {
        browser: {
          type: 'chromium',
        },
      },
    },
  },
  thresholds: {
    'browser_web_vital_lcp': ['p(95)<3000'],    // Largest Contentful Paint < 3s
    'browser_web_vital_fid': ['p(95)<100'],     // First Input Delay < 100ms
  },
};

export default async function userJourneyScenario() {
  const page = browser.newPage();

  try {
    // Navigate to homepage
    await page.goto(baseUrl, {
      waitUntil: 'networkidle',
      timeout: '30s',
    });

    check(page, {
      'page loaded': page.locator('h1').textContent() !== '',
    });

    // Click login link
    await page.locator('a[href="/my_messages.php"]').click();
    await page.waitForSelector('input[name="login"]');

    // Fill login form
    await page.locator('input[name="login"]').type(testUser);
    await page.locator('input[name="password"]').type(testPassword);
    await page.locator('input[type="submit"]').click();

    // Verify login success
    check(page, {
      'logged in': page.locator('h2').textContent().includes('Welcome'),
    });

  } finally {
    page.close();
  }

  sleep(1);
}
