// Simple HTTP GET Load Test
// Generated by: /k6.plan scenario=load target=https://httpbin.org/get sla=p95<400ms
// Updated: Uses environment variables for URL
// Usage: k6 run --env BASE_URL=https://httpbin.org simple-get.js

import http from 'k6/http';
import { check, sleep } from 'k6';

const baseUrl = __ENV.BASE_URL || 'https://httpbin.org';

export const options = {
  stages: [
    { duration: '2m', target: 20 },  // Ramp up to 20 VUs
    { duration: '5m', target: 20 },  // Stay at 20 VUs
    { duration: '2m', target: 0 },   // Ramp down to 0
  ],
  thresholds: {
    'http_req_duration': ['p(95)<400'],    // 95th percentile < 400ms
    'http_req_failed': ['rate<0.01'],      // Error rate < 1%
    'http_reqs': ['rate>10'],              // Minimum 10 req/s
  },
};

export default function simpleGetScenario() {
  const response = http.get(`${baseUrl}/get`, {
    tags: { name: 'httpbin-get' },
    timeout: '30s',
  });

  check(response, {
    'status is 200': (r) => r.status === 200,
    'response time < 400ms': (r) => r.timings.duration < 400,
  });

  sleep(1);
}
