// Multi-Stage Load Test with Complex Scenarios
// Generated by: /k6.plan scenario=stress target=https://httpbin.org profile=aggressive

import http from 'k6/http';
import { check, sleep } from 'k6';

export const options = {
  scenarios: {
    // Warmup phase
    warmup: {
      executor: 'constant-vus',
      vus: 5,
      duration: '1m',
      startTime: '0s',
      gracefulStop: '10s',
    },
    
    // Normal load
    normal_load: {
      executor: 'ramping-vus',
      startVUs: 10,
      stages: [
        { duration: '2m', target: 50 },   // Ramp up
        { duration: '5m', target: 50 },   // Steady state
      ],
      startTime: '1m',
      gracefulStop: '10s',
    },
    
    // Stress phase
    stress_phase: {
      executor: 'ramping-vus',
      startVUs: 50,
      stages: [
        { duration: '3m', target: 200 },  // Increase to stress
        { duration: '5m', target: 200 },  // Sustained stress
        { duration: '3m', target: 500 },  // Beyond capacity
      ],
      startTime: '8m',
      gracefulStop: '30s',
    },
    
    // Recovery phase
    recovery: {
      executor: 'ramping-vus',
      startVUs: 500,
      stages: [
        { duration: '2m', target: 50 },   // Reduce load
        { duration: '2m', target: 0 },    // Cool down
      ],
      startTime: '19m',
      gracefulStop: '10s',
    },
  },
  
  thresholds: {
    'http_req_duration': ['p(95)<800', 'p(99)<2000'],
    'http_req_failed': ['rate<0.05'],    // Allow 5% errors in stress
    'http_reqs': ['rate>50'],
  },
};

export default function multiStageScenario() {
  const response = http.get('https://httpbin.org/delay/1', {
    tags: { name: 'delayed-endpoint' },
    timeout: '30s',
  });

  check(response, {
    'status is 200 or 429': (r) => r.status === 200 || r.status === 429,
    'response is valid': (r) => r.body.length > 0,
  });

  sleep(0.5);  // Aggressive profile: shorter sleep
}
